# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jefferson Daniel
email: jeffersondanielss@gmail.com
description: Desenvolvedor front-end
baseurl: ""
url: "jeffersondanielss.github.io" # the base hostname & protocol for your site
twitter_username: jeffersondss_
github_username:  jeffersondanielss

# Build settings
markdown: kramdown
permalink: /:title/
source: .
destination: ./_site
exclude:
  - node_modules
  - README.md
  - package.json
  - Gruntfile.js
  - .DS_Store
  - LICENSE
sass:
  sass_dir: _sass