# Header
menu:
  #Sobre mim: /sobre-min
  #Projetos: /projetos
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: UA-43996928-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
